package com.ujcms.cms.ext.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class CommentsBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "comments";

    @NotNull
    private Integer id = 0;

    /**
     * 评论用户
     */
    @NotNull
    @Schema(description="评论用户")
    private Integer userId = 0;

    /**
     * 创建日期
     */
    @NotNull
    @Schema(description="创建日期")
    private OffsetDateTime created = OffsetDateTime.now();

    /**
     * IP地址
     */
    @Length(max = 45)
    @NotNull
    @Schema(description="IP地址")
    private String ip = "";

    /**
     * 状态(0:已审核,1:未审核,2:已屏蔽)
     */
    @NotNull
    @Schema(description="状态(0:已审核,1:未审核,2:已屏蔽)")
    private Short status = 1;

    /**
     * 所在文章
     */
    @NotNull
    @Schema(description="所在文章")
    private Integer articleId = 0;

    @Nullable
    private Double positiveLevel;

    /**
     * 评论内容
     */
    @Nullable
    @Schema(description="评论内容")
    private String text;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public OffsetDateTime getCreated() {
        return created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    @Nullable
    public Double getPositiveLevel() {
        return positiveLevel;
    }

    public void setPositiveLevel(@Nullable Double positiveLevel) {
        this.positiveLevel = positiveLevel;
    }

    @Nullable
    public String getText() {
        return text;
    }

    public void setText(@Nullable String text) {
        this.text = text;
    }
}