package com.ujcms.cms.core.domain.base;

import io.swagger.v3.oas.annotations.media.Schema;
import java.io.Serializable;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.Nullable;

/**
 * This class was generated by MyBatis Generator.
 *
 * @author MyBatis Generator
 */
public class BlockBase implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 数据库表名
     */
    public static final String TABLE_NAME = "block";

    @NotNull
    private Integer id = 0;

    /**
     * 站点ID
     */
    @Nullable
    @Schema(description="站点ID")
    private Integer siteId;

    /**
     * 名称
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="名称")
    private String name = "";

    /**
     * 别名
     */
    @Length(max = 50)
    @NotNull
    @Schema(description="别名")
    private String alias = "";

    /**
     * 共享范围(0:本站私有,1:子站点共享,2:全局共享)
     */
    @NotNull
    @Schema(description="共享范围(0:本站私有,1:子站点共享,2:全局共享)")
    private Short scope = 0;

    @Nullable
    private Boolean withLinkUrl = true;

    @Nullable
    private Boolean withSubtitle = false;

    @Nullable
    private Boolean withDescription = false;

    @Nullable
    private Boolean withImage = false;

    @Nullable
    private Boolean withMobileImage = false;

    @Nullable
    private Boolean linkUrlRequired = true;

    @Nullable
    private Boolean subtitleRequired = false;

    @Nullable
    private Boolean descriptionRequired = false;

    @Nullable
    private Boolean imageRequired = false;

    @Nullable
    private Boolean mobileImageRequired = false;

    /**
     * 图片宽度
     */
    @NotNull
    @Schema(description="图片宽度")
    private Integer imageWidth = 300;

    /**
     * 图片高度
     */
    @NotNull
    @Schema(description="图片高度")
    private Integer imageHeight = 200;

    /**
     * 手机端图片宽度
     */
    @NotNull
    @Schema(description="手机端图片宽度")
    private Integer mobileImageWidth = 300;

    /**
     * 手机端图片高度
     */
    @NotNull
    @Schema(description="手机端图片高度")
    private Integer mobileImageHeight = 200;

    @Nullable
    private Boolean recommendable = true;

    @Nullable
    private Boolean enabled = true;

    /**
     * 排序
     */
    @NotNull
    @Schema(description="排序")
    private Short order = 32767;

    @Nullable
    private Boolean withVideo = false;

    @Nullable
    private Boolean videoRequired = false;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Nullable
    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(@Nullable Integer siteId) {
        this.siteId = siteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Short getScope() {
        return scope;
    }

    public void setScope(Short scope) {
        this.scope = scope;
    }

    @Nullable
    public Boolean getWithLinkUrl() {
        return withLinkUrl;
    }

    public void setWithLinkUrl(@Nullable Boolean withLinkUrl) {
        this.withLinkUrl = withLinkUrl;
    }

    @Nullable
    public Boolean getWithSubtitle() {
        return withSubtitle;
    }

    public void setWithSubtitle(@Nullable Boolean withSubtitle) {
        this.withSubtitle = withSubtitle;
    }

    @Nullable
    public Boolean getWithDescription() {
        return withDescription;
    }

    public void setWithDescription(@Nullable Boolean withDescription) {
        this.withDescription = withDescription;
    }

    @Nullable
    public Boolean getWithImage() {
        return withImage;
    }

    public void setWithImage(@Nullable Boolean withImage) {
        this.withImage = withImage;
    }

    @Nullable
    public Boolean getWithMobileImage() {
        return withMobileImage;
    }

    public void setWithMobileImage(@Nullable Boolean withMobileImage) {
        this.withMobileImage = withMobileImage;
    }

    @Nullable
    public Boolean getLinkUrlRequired() {
        return linkUrlRequired;
    }

    public void setLinkUrlRequired(@Nullable Boolean linkUrlRequired) {
        this.linkUrlRequired = linkUrlRequired;
    }

    @Nullable
    public Boolean getSubtitleRequired() {
        return subtitleRequired;
    }

    public void setSubtitleRequired(@Nullable Boolean subtitleRequired) {
        this.subtitleRequired = subtitleRequired;
    }

    @Nullable
    public Boolean getDescriptionRequired() {
        return descriptionRequired;
    }

    public void setDescriptionRequired(@Nullable Boolean descriptionRequired) {
        this.descriptionRequired = descriptionRequired;
    }

    @Nullable
    public Boolean getImageRequired() {
        return imageRequired;
    }

    public void setImageRequired(@Nullable Boolean imageRequired) {
        this.imageRequired = imageRequired;
    }

    @Nullable
    public Boolean getMobileImageRequired() {
        return mobileImageRequired;
    }

    public void setMobileImageRequired(@Nullable Boolean mobileImageRequired) {
        this.mobileImageRequired = mobileImageRequired;
    }

    public Integer getImageWidth() {
        return imageWidth;
    }

    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }

    public Integer getImageHeight() {
        return imageHeight;
    }

    public void setImageHeight(Integer imageHeight) {
        this.imageHeight = imageHeight;
    }

    public Integer getMobileImageWidth() {
        return mobileImageWidth;
    }

    public void setMobileImageWidth(Integer mobileImageWidth) {
        this.mobileImageWidth = mobileImageWidth;
    }

    public Integer getMobileImageHeight() {
        return mobileImageHeight;
    }

    public void setMobileImageHeight(Integer mobileImageHeight) {
        this.mobileImageHeight = mobileImageHeight;
    }

    @Nullable
    public Boolean getRecommendable() {
        return recommendable;
    }

    public void setRecommendable(@Nullable Boolean recommendable) {
        this.recommendable = recommendable;
    }

    @Nullable
    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(@Nullable Boolean enabled) {
        this.enabled = enabled;
    }

    public Short getOrder() {
        return order;
    }

    public void setOrder(Short order) {
        this.order = order;
    }

    @Nullable
    public Boolean getWithVideo() {
        return withVideo;
    }

    public void setWithVideo(@Nullable Boolean withVideo) {
        this.withVideo = withVideo;
    }

    @Nullable
    public Boolean getVideoRequired() {
        return videoRequired;
    }

    public void setVideoRequired(@Nullable Boolean videoRequired) {
        this.videoRequired = videoRequired;
    }
}