# 数据库连接URL
spring.datasource.url: jdbc:mysql://${UJCMS_DB_HOST}/${UJCMS_DB_NAME}?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
# 数据库用户名
spring.datasource.username: ${UJCMS_DB_USER}
# 数据库密码
spring.datasource.password: ${UJCMS_DB_PASSWORD}
